{
  try {
    T result=callable.call();
    listener.onResult(result);
    return result;
  }
 catch (  Exception e) {
    listener.onException(e);
    throw e;
  }
}
