{
  for (  MembershipAction.JoinCallback callback : callbacks) {
    try {
      callback.onSuccess();
    }
 catch (    Exception e) {
      logger.error("unexpected error during [{}]",e,source);
    }
  }
}
