{
  try {
    return constructor.newInstance(args);
  }
 catch (  InvocationTargetException e) {
    throw e.getCause();
  }
}
