{
  if (e.getCause() instanceof BindException) {
    return;
  }
  logger.warn("failure caught",e.getCause());
}
