{
  RestClient.SyncResponseListener syncResponseListener=new RestClient.SyncResponseListener(10000);
  Response mockResponse=mockResponse();
  syncResponseListener.onSuccess(mockResponse);
  Response response=syncResponseListener.get();
  assertSame(response,mockResponse);
  try {
    syncResponseListener.onSuccess(mockResponse);
    fail("get should have failed");
  }
 catch (  IllegalStateException e) {
    assertEquals(e.getMessage(),"response is already set");
  }
  response=syncResponseListener.get();
  assertSame(response,mockResponse);
  RuntimeException runtimeException=new RuntimeException("test");
  syncResponseListener.onFailure(runtimeException);
  try {
    syncResponseListener.get();
    fail("get should have failed");
  }
 catch (  IllegalStateException e) {
    assertEquals("response and exception are unexpectedly set at the same time",e.getMessage());
    assertNotNull(e.getSuppressed());
    assertEquals(1,e.getSuppressed().length);
    assertSame(runtimeException,e.getSuppressed()[0]);
  }
}
