{
  try {
    runInternal();
  }
 catch (  Exception ex) {
    if (lastThrownException == null || sameException(lastThrownException,ex) == false) {
      indexService.logger.warn("failed to run task {} - supressing re-occuring exceptions unless the exception changes",ex,toString());
      lastThrownException=ex;
    }
  }
 finally {
    onTaskCompletion();
  }
}
